name: fileweightloss
description: File Weight Loss vous permet de compresser rapidement et facilement vos fichiers audio et vidéo.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.5
  dotted_border: ^2.1.0
  desktop_drop: ^0.5.0
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.8
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.5
  http: ^1.2.2
  path: ^1.9.0
  archive: ^4.0.2
  macos_ui: ^2.0.9
  fluent_ui: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
