name: fileweightloss
description: File Weight Loss vous permet de compresser rapidement et facilement vos fichiers audio et vidéo.
publish_to: none
version: 2.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.5
  dotted_border: ^2.1.0
  desktop_drop: ^0.5.0
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  path: ^1.9.0
  archive: ^4.0.2
  get_storage: ^2.1.1
  flutter_localizations:
    sdk: flutter
  hotkey_manager: ^0.2.3
  flutter_local_notifications: ^18.0.1
  shadcn_ui: ^0.18.3
  window_manager: ^0.4.3
  package_info_plus: ^8.2.1
  flutter_markdown: ^0.7.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

msix_config:
  display_name: File Weight Loss
  publisher_display_name: Elie Z.
  publisher: CN=4B7C716A-26DD-4533-B881-FD85EDCA9936
  identity_name: 28115JohanStickman.FileWeightLoss
  msix_version: 2.0.0.0
  logo_path: assets/app_icon.png
  capabilities: internetClient
  store: true